### ISSUE TITLE
stopped working - application error

### ISSUE THREAD

**Issue by mthrum** [Aveek-Saha/Online-Chess#1]
This great simple chess game stopped working altogether. Would love a fix to continue playing with some folks who are covid confined. Thanks !

**Comment by Aveek-Saha** [comment]
The application is deployed on Heroku free tier, and it looks like the free quota for this month has finished. If you want to continue playing you could deploy your own instance of this app on Heroku using a node js environment!

**Comment by mthrum** [comment]
Thank you for the prompt feedback. Suggestion welcome but way above my pay grade :-)
