### ISSUE TITLE
can u please help me?

### ISSUE THREAD

**Issue by BrexeGT** [Aveek-Saha/Online-Chess#2]
Hello Owner, I've an issue on connecting to the web, due to I'm still learning can you tell me how should i connect to it? Thanks

**Comment by Aveek-Saha** [comment]
The website is hosted on Heroku free tier and usually it runs out of resources by the end of the month. This may be why you are not able to connect.
Once you are able to load the page, just enter any room number and share that room number with your friend. Once both of you are in the same room you can start playing

**Comment by BrexeGT** [comment]
Oh thanks I thought I can use my own domain to host it.
